<!doctype html>
<html>
  <head>
  </head>
  <body>
    <nav>
  		<?php include "bloques/navegacion.php" ?>
    </nav>
    <main>
    	<table>
      	<thead>
        	<tr>
          	<th>Nombre</th>
            <th>Apellidos</th>
            <th>Email</th>
            <th>Direccion</th>
          </tr>
        </thead>
        <tbody>
        	<tr>
          	<td>Nombre</td>
            <td>Apellidos</td>
            <td>Email</td>
            <td>Direccion</td>
          </tr>
          <tr>
          	<td>Nombre</td>
            <td>Apellidos</td>
            <td>Email</td>
            <td>Direccion</td>
          </tr>
          <tr>
          	<td>Nombre</td>
            <td>Apellidos</td>
            <td>Email</td>
            <td>Direccion</td>
          </tr>
          <tr>
          	<td>Nombre</td>
            <td>Apellidos</td>
            <td>Email</td>
            <td>Direccion</td>
          </tr>
        </tbody>
      </table>
    </main>
  </body>
</html>
