CREATE USER 
'blogphp'@'localhost' 
IDENTIFIED  BY 'Blogphp123$';

GRANT USAGE ON *.* TO 'blogphp'@'localhost';

ALTER USER 'blogphp'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON blogphp.* 
TO 'blogphp'@'localhost';

FLUSH PRIVILEGES;

