CREATE USER 
'futbol2526'@'localhost' 
IDENTIFIED  BY 'Futbol2526$';

GRANT USAGE ON *.* TO 'futbol2526'@'localhost';

ALTER USER 'futbol2526'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;


GRANT ALL PRIVILEGES ON futbol2526.* 
TO 'futbol2526'@'localhost';

FLUSH PRIVILEGES;

